# Site settings
title: Bremco
description: |
  A residential property
  management and development
  company
owner: Bremco Associates LLC
first_published: 2016
email: boulet109@comcast.net
baseurl: ""
url: "http://yourdomain.com"
social:
  linkedin-square: https://linkedin.com/in/markbouloutian
  email: mailto:boulet109@comcast.net

# Build settings
markdown: kramdown
#sass:
#  style: compressed
